aliases:
  United Nations Environment Programme: UNEP
  United Nations Human Settlements Programme: UN-Habitat
  United Nations Office on Drugs and Crime: UNODC
  Office of the High Commissioner for Human Rights: OHCHR
parents:
  IFC: World Bank Group
  MIGA: World Bank Group
  ICSID: World Bank Group
  World Bank: World Bank Group
