"""AtlasVault v1 reference implementation.

This package provides the Phase 1 Python reference implementation for encrypted
vault metadata, key wrapping, and record encryption. It does not implement cloud
sync, account authentication, platform key stores, or data migration.
"""

from vaultsync.crypto import (
    create_vault_metadata,
    decrypt_record_payload,
    derive_record_key,
    derive_recovery_wrapping_key,
    derive_wrapping_key_argon2id,
    encode_recovery_key,
    encrypt_record_payload,
    generate_recovery_key,
    generate_vault_key,
    parse_recovery_key,
    recovery_wrap_v2_aad,
    unwrap_vault_key,
    unwrap_vault_key_with_recovery,
    wrap_vault_key,
    wrap_vault_key_with_recovery,
)
from vaultsync.export import (
    AtlasVaultExport,
    UnsupportedExportVersion,
    VaultExportError,
    deserialize_vault_export,
    read_atlasvault_export,
    serialize_vault_export,
    serialize_vault_export_bytes,
    write_atlasvault_export,
)
from vaultsync.format import (
    Argon2idParams,
    RecoveryKeyError,
    RecoveryKeyWrapHKDFParams,
    RecoveryKeyWrapV2,
    UnsupportedVaultVersion,
    VersionedWrappedKey,
    VaultAuthenticationError,
    VaultCryptoError,
    VaultCryptoSuite,
    VaultFormatError,
    VaultKeyUnwrapError,
    VaultMetadata,
    WrappedKey,
    deserialize_vault_metadata,
    serialize_vault_metadata,
)
from vaultsync.migration import (
    MigrationDryRunReport,
    MigrationResult,
    MigrationSafetyError,
    MigrationSourceError,
    build_encrypted_records_from_sources,
    dry_run_sources,
    load_saved_searches_source,
    load_tracker_source,
    migrate_sources_to_encrypted_records,
    write_staged_export,
    write_staged_local_store,
)
from vaultsync.records import (
    EncryptedRecord,
    PlaintextRecord,
    RecordFormatError,
    UnsupportedRecordVersion,
    deserialize_encrypted_record,
    serialize_encrypted_record,
)
from vaultsync.store import (
    LocalVaultStore,
    UnsupportedStoreVersion,
    VaultStoreError,
    deserialize_local_store,
    read_local_store,
    serialize_local_store,
    serialize_local_store_bytes,
    write_local_store,
)

__all__ = [
    "Argon2idParams",
    "AtlasVaultExport",
    "EncryptedRecord",
    "LocalVaultStore",
    "MigrationDryRunReport",
    "MigrationResult",
    "MigrationSafetyError",
    "MigrationSourceError",
    "PlaintextRecord",
    "RecordFormatError",
    "RecoveryKeyError",
    "RecoveryKeyWrapHKDFParams",
    "RecoveryKeyWrapV2",
    "UnsupportedExportVersion",
    "UnsupportedRecordVersion",
    "UnsupportedStoreVersion",
    "UnsupportedVaultVersion",
    "VersionedWrappedKey",
    "VaultAuthenticationError",
    "VaultCryptoError",
    "VaultCryptoSuite",
    "VaultExportError",
    "VaultFormatError",
    "VaultKeyUnwrapError",
    "VaultMetadata",
    "VaultStoreError",
    "WrappedKey",
    "build_encrypted_records_from_sources",
    "create_vault_metadata",
    "decrypt_record_payload",
    "derive_record_key",
    "derive_recovery_wrapping_key",
    "derive_wrapping_key_argon2id",
    "deserialize_encrypted_record",
    "deserialize_local_store",
    "deserialize_vault_export",
    "deserialize_vault_metadata",
    "dry_run_sources",
    "encode_recovery_key",
    "encrypt_record_payload",
    "generate_recovery_key",
    "generate_vault_key",
    "load_saved_searches_source",
    "load_tracker_source",
    "migrate_sources_to_encrypted_records",
    "parse_recovery_key",
    "read_atlasvault_export",
    "read_local_store",
    "recovery_wrap_v2_aad",
    "serialize_encrypted_record",
    "serialize_local_store",
    "serialize_local_store_bytes",
    "serialize_vault_export",
    "serialize_vault_export_bytes",
    "serialize_vault_metadata",
    "unwrap_vault_key",
    "unwrap_vault_key_with_recovery",
    "wrap_vault_key",
    "wrap_vault_key_with_recovery",
    "write_atlasvault_export",
    "write_local_store",
    "write_staged_export",
    "write_staged_local_store",
]
